backend:
  name: github
  branch: master
  repo: blog-house/blog-house
  publish_mode: editorial_workflow

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

slug:
  encoding: 'ascii'
  clean_accents: true

locale: 'zh_Hans'

collections:
  - name: 'articles'
    label: '文章'
    folder: 'source/_posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '发表日期', name: 'date', widget: 'datetime' }
      - { label: '标签', name: 'tags', widget: 'list', hint: '每个标签之间使用英文逗号,分割' }
      - {
          label: '摘要',
          name: 'excerpt',
          widget: 'text',
          required: false,
          hint: '字数控制在50到80字效果最佳'
        }
      - { label: '内容', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: '页面'
    folder: 'source/_pages'
    create: true
    slug: '{{pageSlug}}'
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - {
          label: '页面路径名称',
          name: 'pageSlug',
          widget: 'string',
          hint: '纯英文数字以及下划线组合，如果填写“test”，那么此页面的 URL 将会是 “https://xxx/test”',
          pattern: ['^[\d\w_-]+$', '纯英文数字以及下划线组合']
        }
      - { label: '内容', name: 'body', widget: 'markdown' }
  - name: 'specialContent'
    label: '特殊内容'
    files:
      - name: 'footerConfiguration'
        label: '底栏配置'
        file: 'src/footer-configuration.yml'
        fields:
          - name: 'leftContent'
            label: '左侧内容'
            widget: 'string'
          - name: 'rightContent'
            label: '右侧内容'
            widget: 'string'
      - name: 'homePageConfiguration'
        label: '首页组件配置'
        file: 'src/home-page-configuration.yml'
        fields:
          - name: 'tabsContent'
            label: '标签页内容'
            widget: 'list'
            fields:
              - {
                  label: '图标名',
                  name: 'icon',
                  widget: 'string',
                  hint: '必须填写正确的图标名，否则无法正确显示，具体请见文档'
                }
              - { label: '内容', name: 'content', widget: 'markdown' }
