backend:
  name: github
  branch: master
  repo: blog-house/blog-house
  publish_mode: editorial_workflow

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

slug:
  encoding: 'ascii'
  clean_accents: true

locale: 'zh_Hans'

collections:
  - name: 'articles'
    label: '文章'
    folder: 'source/_posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '发表日期', name: 'date', widget: 'datetime' }
      - { label: '标签', name: 'tags', widget: 'list', hint: '每个标签之间使用英文逗号,分割' }
      - {
          label: '摘要',
          name: 'excerpt',
          widget: 'text',
          required: false,
          hint: '如果摘要留空，则会自动截取内容的前至多 160 个文字作为摘要'
        }
      - { label: '内容', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: '页面'
    folder: 'source/_pages'
    create: true
    slug: '{{pageSlug}}'
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - {
          label: '路径名称',
          name: 'pageSlug',
          widget: 'string',
          hint: '纯英文数字以及下划线组合，如果填写“my-page”，那么此页面的 URL 将会是 “https://xxx/my-page”',
          pattern: ['^[\d\w_-]+$', '纯英文数字以及下划线组合']
        }
      - { label: '内容', name: 'body', widget: 'markdown' }
  - name: 'configuration'
    label: '博客配置'
    editor:
      preview: false
    files:
      - name: 'basicConfiguration'
        label: '博客基本配置'
        file: 'config/basic-configuration.yml'
        fields:
          - name: 'blogName'
            label: '博客名称'
            widget: 'string'
            hint: '用于显示在导航栏左侧，以及标题、Sitemap 等处'
          - name: 'authorName'
            label: '作者名称'
            widget: 'string'
            hint: '你的大名，主要显示在首页卡片中'
          - name: 'url'
            label: '博客 URL'
            widget: 'string'
            hint: '用于 Sitemap 的生成，例子：https://example.com'
          - name: 'description'
            label: '简介'
            widget: 'string'
            hint: '对于你或你的博客的简要介绍，用于 SEO、首页卡片的文字，长度最好不要超过 10 个汉字'
          - name: 'dir'
            label: '书写方向'
            widget: 'select'
            hint: '博客主要使用的文字的书写方向，主要用于 Webmanifest 中作为标识'
            default: 'ltr'
            options:
              - { label: '左到右', value: 'ltr' }
              - { label: '右到左', value: 'rtl' }
              - { label: '自动', value: 'auto' }
          - name: 'language'
            label: '语言'
            widget: 'string'
            hint: '博客主要使用的语言'
          - name: 'analytic'
            label: '统计'
            widget: 'object'
            hint: '利用谷歌、百度的统计服务，获取你的博客访客情况'
            required: false
            fields:
              - label: 'Google Analytics Measurement ID'
                name: 'gaMeasurementId'
                widget: 'string'
                hint: '谷歌统计的 Measurement ID，参见谷歌统计的官方文档'
              - label: '百度统计 ID'
                name: 'baiduId'
                widget: 'string'
                hint: '百度统计的 ID，参见百度统计的官方文档'
          - name: 'comment'
            label: '评论区'
            widget: 'object'
            fields:
              - label: '评论区插件'
                name: 'type'
                widget: 'select'
                options:
                  - { label: 'Utterances', value: 'utterances' }
                  - { label: '关闭', value: 'none' }
      - name: 'navConfiguration'
        label: '导航栏配置'
        file: 'config/nav-configuration.yml'
        fields:
          - name: 'navItems'
            label: '导航栏项目'
            widget: 'list'
            fields:
              - label: '类型'
                name: 'type'
                widget: 'select'
                hint: '不同类型的导航栏项目有着不同的功能'
                options:
                  - { label: '首页', value: 'home' }
                  - { label: '文章', value: 'articles' }
                  - { label: '标签', value: 'tags' }
                  - { label: '页面', value: 'page' }
              - label: '标题'
                name: 'caption'
                widget: 'string'
                hint: '对应这个导航栏项目的按钮文本'
              - label: '路径名称'
                name: 'slug'
                required: false
                widget: 'string'
                hint: '除了"页面"选项都不需要填写，"页面"选项必须填写，对应需要导航到的页面的路径名称'
      - name: 'tagsConfiguration'
        label: '标签配置'
        file: 'config/tags-configuration.yml'
        fields:
          - name: 'tags'
            label: '标签'
            widget: 'list'
            fields:
              - {
                  label: '路径名称',
                  name: 'slug',
                  widget: 'string',
                  hint: '纯英文数字以及下划线组合，如果填写“my-tag”，那么此标签页面的 URL 将会是 “https://xxx/tags/my-tag”',
                  pattern: ['^[\d\w_-]+$', '纯英文数字以及下划线组合']
                }
              - {
                  label: '名称',
                  name: 'name',
                  widget: 'string',
                  hint: '用于显示在文章的标签部分中，同时也用在编写文章时指定标签'
                }
              - { label: '简介', name: 'description', widget: 'text', required: false }
      - name: 'homePageConfiguration'
        label: '首页组件配置'
        file: 'config/home-page-configuration.yml'
        fields:
          - name: 'contact'
            label: '卡片的联系方式'
            widget: 'list'
            fields:
              - label: '类型'
                name: 'type'
                widget: 'select'
                options:
                  - { label: '位置', value: 'location' }
                  - { label: 'GitHub 用户名', value: 'github' }
              - label: '值'
                name: 'text'
                widget: 'string'
          - name: 'tabsContent'
            label: '标签页内容'
            widget: 'list'
            fields:
              - label: '图标名'
                name: 'icon'
                widget: 'string'
                hint: '必须填写正确的图标名，否则无法正确显示，具体请见文档'
              - label: '内容'
                name: 'content'
                widget: 'markdown'
      - name: 'footerConfiguration'
        label: '底栏配置'
        file: 'config/footer-configuration.yml'
        fields:
          - name: 'leftContent'
            label: '左侧内容'
            widget: 'markdown'
          - name: 'rightContent'
            label: '右侧内容'
            widget: 'markdown'
