blogName: Darky's Blog
authorName: darkyzhou
url: https://darkyzhou.net
description: 别把看重的东西附上无边的价值
dir: ltr
language: zh-CN
analytics:
  blockedDomains:
    - 'localhost'
  blockedUAs:
    - 'googlebot'
    - 'baiduspider'
    - 'sogou web spider'
    - 'bingbot'
    - 'duckduckbot'
    - 'yandexbot'
    - 'yahoo! slurp'
  baiduId: f60a9a2b48d8e5dd35145c273edec8ef
  gaMeasurementId: UA-169813168-1
comments:
  - type: utterances
    repository: darkyzhou/blog-comments
    issueTerm: title
    label: ''
    theme: github-dark
  - type: none
algolia:
  enabled: false
  index: 'darky_blog'
  applicationId: 'XP3BDSDXS9'
  searchOnlyApiKey: 'e225d83ac2d8b1aa0d8d573ba1be5be5'
  adminApiKey: ''
