blogName: 'Example Blog'
authorName: 'darkyzhou'
url: 'https://example.com'
description: 'This is an example blog, enjoy it!'
dir: 'ltr'
lang: 'zh-CN'
analytics:
  gaMeasurementId: ''
  baiduId: ''
comment:
  type: utterances
