blogName: Darky's Blog
authorName: darkyzhou
url: https://darkyzhou.net
description: 别把看重的东西附上无边的价值
dir: ltr
language: zh-CN
analytics:
  blockedDomains:
    - 'localhost'
  blockedUAs:
    - 'googlebot'
    - 'baiduspider'
    - 'sogou web spider'
    - 'bingbot'
    - 'duckduckbot'
    - 'yandexbot'
    - 'yahoo! slurp'
  gaMeasurementId: ''
  baiduId: ''
  umamiId: ''
comment:
  type: 'giscus'
  config:
    repo: 'darkyzhou/blog-comments'
    repoId: 'R_kgDOGmBUJQ'
    category: 'General'
    categoryId: 'DIC_kwDOGmBUJc4CV92v'
    mapping: 'og:title'
    theme: 'dark_tritanopia'
    lang: 'zh-CN'
    loading: 'eager'
algolia:
  enabled: 'true'
  index: 'darky_blog'
  applicationId: 'XP3BDSDXS9'
  searchOnlyApiKey: 'e225d83ac2d8b1aa0d8d573ba1be5be5'
  adminApiKey: ''
