blogName: 'Example Blog'
authorName: 'darkyzhou'
url: 'https://example.com'
description: 'This is an example blog, enjoy it!'
dir: 'ltr'
language: 'zh-CN'
analytics:
  blockedDomains:
    - 'localhost'
  blockedUAs:
    - 'googlebot'
    - 'baiduspider'
    - 'sogou web spider'
    - 'bingbot'
    - 'duckduckbot'
    - 'yandexbot'
    - 'yahoo! slurp'
  gaMeasurementId: ''
  baiduId: ''
comments:
  - type: 'utterances'
    repository: 'blog-house/blog-house'
    issueTerm: 'title'
    label: ''
    theme: 'github-dark'
  - type: 'none'
algolia:
  enabled: false
  index: 'blog_house'
  applicationId: ''
  searchOnlyApiKey: ''
  adminApiKey: ''
