categories:
  - slug: 'web-frontend'
    name: '前端修炼手册'
    description: 'Web 前端有什么难的，不就是写点 CSS 和 JavaScript……哎最近白头发又变多了……'
  - slug: 'linux'
    name: 'Linux 研究日志'
    description: 'Linux 容器是我比较喜欢折腾的方向'
  - slug: 'cloud-native'
    name: '云原生'
    description: '虽然云原生是一个比 Kubernetes 运维更大的话题，但我还是想说：天若运维天亦老，人间正道是沧桑！'
  - slug: 'programming-miscellaneous'
    name: '编程杂谈'
    description: '老河兵们都有一套自己的经验准则，我虽然不老，却也有些小发现想分享出来'
  - slug: 'thoughts'
    name: '随笔'
    description: '和编程技术不那么强相关的一些想法'
