_markdownFields:
  - 'left'
  - 'right'
left: '别把看重的东西附上无边的价值'
right: '© 2021 darkyzhou. Powered by [Blog House](https://github.com/blog-house/blog-house). [粤 ICP 备 2022082297 号](https://beian.miit.gov.cn/).'
additional:
  - type: 'page'
    icon: 'Friendship16'
    caption: '友情链接'
    target: 'links'
  - type: 'rss'
    caption: 'RSS'
  - type: 'link'
    icon: 'LogoGithub16'
    caption: 'darkyzhou'
    target: 'https://github.com/darkyzhou'
