_markdownFields:
  - tabsContent.*.content
avatar: /images/uploads/seele.jpg
contact:
  - type: Location16
    text: Shenzhen
  - type: LogoGithub16
    text: darkyzhou
tabsContent:
  - icon: InformationSquare32
    content: >-
      我叫 Darkyzhou，以前用的 ID 是 Darkyoooooo。由于一则奇特的食用油广告，朋友们戏称我为“达克油”，虽然我从未涉足制油行业。我出生于 2001 年，成长于粤北一个并不太平静的小山城。


      自小我便酷爱各种形式的创作，乐于分享自己内心的奇思妙想。在小学期间，我尝试过学习素描和漫画，但最终发现自己并不适合这条路。


      小学毕业那个夏天，我开始接触 Minecraft 模组开发，并购买了一本 Java 编程书籍。在完成了我第一款模组并亲眼见证其在游戏中的表现后，我决定将计算机技术作为我的终身爱好和职业方向。


      后来，我进入了广州的一所大学，主修软件工程，并加入了学院课程平台的开发团队。经过不懈努力，我最终担任了团队的技术负责人。除了编程，我还喜欢玩手游，收集手办和电子产品（所谓的“捡垃圾”）。


      毕业后，我成为了一名 Web 前端工程师，目前在飞书文档工作。如果你想要了解更多关于我的信息，请阅读[关于](/about)。
  - icon: Milestone32
    content: >-
      我的兴趣颇为广泛：

      - 编程。虽然我的职场主战场在 Web 前端领域，但我的技能远不止于此。我认为，程序员应当具备开阔的视野，这使得我不断拓展自己的技术栈，积累更深更广的技术思想。

      - 手游。尽管每每让钱包大出血，我还是难以抗拒其魅力。或许有人会好奇，为何不投身于 PC 或是主机游戏的怀抱？这里我不得不为自己辩驳几句：我的闲暇时光零散且短暂，以至于那台曾费心组装的高性能游戏电脑，最终只能默默在一旁积灰。更不用说，我深陷二次元的世界，且我的空闲时间碎片化严重，难以投入到时间密集型的单机大作中。

      - 收藏手办。对我来说，手办不仅仅是一种视觉上的享受，它们的魅力在于能触摸到的美、角色的神态、完美的身姿线条，以及作为工艺品的细腻。这些美好，足以让我反复欣赏，也能让我从容应对来自内心的疑问：这样的投入是否值得。可惜的是，宿舍的桌面空间有限，而我的兴趣却广泛至极，已无法容纳更多的手办收藏。
  - icon: Code32
    content: |
      在我刚刚踏上编程的旅途时，Java 便是我所接触的第一门编程语言。我认为，对于初探编程世界的新手而言，Java 比起 C 或 C++ 来说，无疑是更为友好的选择。它巧妙地隐藏了那些令初学者头疼的内存访问细节，让我们得以将注意力完全投入到数据类型、控制流、类、接口以及对象等编程的基石之上。可以说，Java 为我奠定了坚实的编程基础。因此，当我踏入大学面对 C 和 C++ 语言的课程时，我能够以惊人的轻松度掌握它们。

      大学之后，我选择了以 Web 前端为新的起点，可以说是一路上有声有色。你若问起现代前端技术，我总能给你来上一两句，算得上略懂一二。至于我偏爱哪个框架？Angular，毫无疑问。无论是实习还是正式工作，我的经历不断向我证明，Angular 仿佛是 Web 前端框架之中的“大成者”。以 React 为例，尽管它广受好评，但开发者们似乎总是不自觉地向其添加各种模块化特性，例如依赖注入、异步模块、控制反转等等，正是这些特性让 React 逐渐靠拢于 Angular。

      我的探索并不止步于此。举个例子，我的本科毕业论文便是运用 Golang 和 Rust 两种语言完成的，我认为它们都是相当出色的编程语言。此外，我还利用 Rust 开发了一款网络网关程序，它能够管理我所有局域网设备的网络流量，并提供了 DNS 加速与广告过滤功能。更多关于这一项目的详情，欢迎阅读[装备](/gears)。

      然而，仅凭上述几点，似乎难以全面展示我所了解的。[与那些专注于狭窄领域的“刺猬”们不同，我更像是一只对世界上的一切都充满好奇的“狐狸”](/articles/i-am-a-fox)。
