_markdownFields:
  - tabsContent.*.content
avatar: /images/uploads/seele-bloghouse-opt.jpg
background: /images/uploads/background-bloghouse-opt.jpg
contact:
  - type: Location16
    text: Shenzhen
  - type: LogoGithub16
    text: darkyzhou
tabsContent:
  - icon: InformationSquare32
    content: >-
      我叫 Darkyzhou，以前的 ID 是 Darkyoooooo，也可以简写成
      Darky。朋友们因为一个奇怪的食用油广告，总是称我为“达克油”，但其实我不会制油。我生于 2001 年，在粤北的一座不算安静的小山城里。


      六年级毕业后，想找些事情做，于是乘着学习 Minecraft 模组开发的道，买了本学习 Java 的书。我平凡的一生就此与计算机这项人类伟大的发明缠上了关系。也是因为模组开发接触到了 mcbbs.net，认识了在上面活跃过的许多志同道合的伙伴，至今仍有联系的不下十个人，他们或许也算是我在这虚无的网络世界里保持联系最久的一批人了。


      可惜的是，初中的我编程学得太慢，有时也会缺乏动力，因此并没有掌握很多的知识。上了高中之后，由于是一所封闭寄宿高中，我没有任何时间能够继续接触电脑，学习编程。所以这三年我基本上都在死啃书本，一心备战高考了。


      后来，我就读于广州某高校的软件工程系，最近加入了学院的某课程平台的开发团队，经过奋斗，成为了其中前端团队的负责人。除了写代码，我平时还喜欢玩手游，收集手办、电子产品（也就是俗称的“捡垃圾”）。


      现在，我已经毕业，作为 Web 前端工程师工作。


      如果你想知道更多关于我的信息，请阅读[“关于”页面](/about)。
  - icon: Milestone32
    content: >-
      我的爱好不算狭窄：

      - 写点代码。饭碗在 Web 前端，不过会的不止 Web 前端，因为我觉得程序员需要具备开阔的视野。

      - 玩点手游。虽然很心疼钱包。有人也许会问，为什么不玩 PC 游戏？主机游戏也不错啊？请容我辩解一番：我的空闲时间非常琐碎，以至于我曾经配过一台不错的游戏 PC，但就摆在角落吃灰了半年。更糟的是，我竟然是个二次元。而且平时的空闲时间比较碎片化，没有办法支撑我玩一些单机大作。

      - 收集手办。对我而言，手办就是一种看得见，摸得着的美。这种美可以是人物神情上的美、可以是身材曲线的美、可以是单纯作为工艺品而言的精细美。这种美经得起眼睛的反复推敲，经得起脑子里质问花这些钱是否值得的声音的追责。只可惜宿舍的桌子太小，我的爱好又太广泛，不足以摆下更多的手办。
  - icon: Code32
    content: |
      我的编程生涯从 Web 前端开始：

      - HTML、CSS、JavaScript、TypeScript。
      - Angular、React、Svelte、Vue。
      - Webpack、Vite。

      后来，对其他领域也产生了兴趣：

      - Golang
      - Rust
      - 云原生
      - Linux 容器技术

      单纯列举这些并不能囊括我知道的东西，因为太琐碎了。
