_markdownFields:
  - 'tabsContent.*.content'
avatar: '/images/uploads/avatar.jpg'
background: '/images/uploads/background.jpg'
contact:
  - type: Location16
    text: Guangzhou
  - type: LogoGithub16
    text: darkyzhou
tabsContent:
  - icon: InformationSquare32
    content: 'Here is my self-introduction: ...'
  - icon: Milestone32
    content: 'I love programming, collecting xxx...'
  - icon: Code32
    content: "My main programming language is TypeScript and in my mind it's the best programming language in the world! My main programming language is TypeScript and in my mind it's the best programming language in the world! My main programming language is TypeScript and in my mind it's the best programming language in the world! My main programming language is TypeScript and in my mind it's the best programming language in the world! My main programming language is TypeScript and in my mind it's the best programming language in the world! My main programming language is TypeScript and in my mind it's the best programming language in the world! My main programming language is TypeScript and in my mind it's the best programming language in the world!"
