tabsContent:
  - icon: message
    content: 'Here is my self-introduction: ...'
  - icon: heart
    content: 'I love programming, collecting xxx...'
  - icon: code
    content: 'My main programming language is TypeScript and in my mind it"s the best programming language in the world!'
